# Query to list all products
query ListProducts @auth(level: USER) {
  products {
    id
    name
    price
  }
}

# Query to get a specific product by its code bar (id)
query GetProductById($id: String!) @auth(level: USER) {
  product(id: $id) {
    id
    name
    price
  }
}

# Query to list all fruits/vegetables
query ListFruits @auth(level: USER) {
  fruits {
    id
    name
    pricePerKg
  }
}

# Query to get a specific fruit by its id
query GetFruitById($id: String!) @auth(level: USER) {
  fruit(id: $id) {
    id
    name
    pricePerKg
  }
}

# Query to list factures for a specific user
query ListFactures($userId: String!) @auth(level: USER) {
  factures(where: { userId: { eq: $userId } }, orderBy: [{ createdAt: DESC }]) {
    id
    totalPrice
    createdAt
  }
}

# Query to get regular product items of a facture
query GetFactureItems($factureId: UUID!) @auth(level: USER) {
  factureItems(where: { factureId: { eq: $factureId } }) {
    id
    quantity
    product {
      id
      name
      price
    }
  }
}

# Query to get fruit/veg items of a facture
query GetFactureFruitItems($factureId: UUID!) @auth(level: USER) {
  factureFruitItems(where: { factureId: { eq: $factureId } }) {
    id
    weight
    fruit {
      id
      name
      pricePerKg
    }
  }
}