// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2RG8MNIvdx1FYBAtsqbSL8yWSx0cEjzM',
    appId: '1:478265590110:web:de707cdddbf64ad2070fcf',
    messagingSenderId: '478265590110',
    projectId: 'fir-auth-6394d',
    authDomain: 'fir-auth-6394d.firebaseapp.com',
    databaseURL: 'https://fir-auth-6394d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-auth-6394d.firebasestorage.app',
    measurementId: 'G-FEGEQHV351',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv3a9GVRDv7ruXSLovoq2NREm3HQDuYd8',
    appId: '1:478265590110:android:b1abb81648a9bfb3070fcf',
    messagingSenderId: '478265590110',
    projectId: 'fir-auth-6394d',
    databaseURL: 'https://fir-auth-6394d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-auth-6394d.firebasestorage.app',
  );
}
